# Generated by Django 3.2.1 on 2021-05-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_num', models.IntegerField(default=0)),
                ('quiz_question', models.CharField(max_length=500)),
                ('quiz_answer', models.CharField(max_length=100)),
                ('quiz_hint', models.CharField(max_length=500)),
            ],
        ),
    ]
