# Generated by Django 3.2.1 on 2021-05-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_questions',
            name='quiz_num',
        ),
    ]
