# Generated by Django 3.2.1 on 2021-05-12 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_remove_quiz_questions_quiz_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz_answer',
        ),
    ]
